nw/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [
    url(r'^django-admin/', admin.site.urls),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r'', include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from __future__ import absolute_import, unicode_literals

import requests

from wagtail.contrib.forms.edit_handlers import FormSubmissionsPanel

from django.db import models

from modelcluster.fields import ParentalKey


from wagtail.core.models import Orderable, Page
from wagtail.core.fields import RichTextField, StreamField
from wagtail.admin.edit_handlers import FieldPanel
#from django.shortcuts import render

from wagtail.snippets.models import register_snippet

from wagtail.images.edit_handlers import ImageChooserPanel

from taggit.models import TaggedItemBase
from taggit.managers import TaggableManager



from modelcluster.fields import ParentalKey
from wagtail.admin.edit_handlers import (
    FieldPanel, FieldRowPanel,
    InlinePanel, MultiFieldPanel
)

from wagtail.contrib.forms.models import AbstractEmailForm, AbstractFormField

from modelcluster.models import ClusterableModel

class FormField(AbstractFormField):
    page = ParentalKey('HomePage', on_delete=models.CASCADE, related_name='form_fields')


class HomePage(AbstractEmailForm):
    body = RichTextField(blank=True)
    intro = RichTextField(blank=True)
    thank_you_text = RichTextField(blank=True)
    intro_support = RichTextField(blank=True)

    content_panels = AbstractEmailForm.content_panels + [
        FormSubmissionsPanel(),
        FieldPanel('body', classname="full"),
        FieldPanel('intro', classname="full"),
        FieldPanel('intro_support', classname="full"),
        InlinePanel('form_fields', label="Form fields"),
        FieldPanel('thank_you_text', classname="full"),
        MultiFieldPanel([
            FieldRowPanel([
                FieldPanel('from_address', classname="col6"),
                FieldPanel('to_address', classname="col6"),
            ]),
            FieldPanel('subject'),
        ], "Email"),
    ]

    def get_context(self, request):
        context = super(HomePage, self).get_context(request)
        context['number'] = 23;
        # Call the API to get numbers, current only use day
        response = requests.get("https://visitor.express/api/v1/health/")
        health = response.json()
        year = health['month']
        context['bookings_year'] = year['bookings']
        context['visitors_year'] = year['visitors']
        context['access_queries_year'] = year['access_queries']
        month = health['month']
        context['bookings_month'] = month['bookings']
        context['visitors_month'] = month['visitors']
        context['access_queries_month'] = month['access_queries']
        week = health['week']
        context['bookings_week'] = week['bookings']
        context['visitors_week'] = week['visitors']
        context['access_queries_week'] = week['access_queries']
        day = health['day']
        context['bookings_day'] = day['bookings']
        context['visitors_day'] = day['visitors']
        context['access_queries_day'] = day['access_queries']
        return context


class CaseStudySnippetTag(TaggedItemBase):
    content_object = ParentalKey('home.CaseStudySnippet', on_delete=models.CASCADE, related_name='tagged_items')

@register_snippet
class CaseStudySnippet(ClusterableModel):
    title = models.CharField(max_length=255, blank=True)
    url = models.URLField(null=True, blank=True)
    text = models.CharField(max_length=255)
    body = RichTextField(blank=True)
    active = models.BooleanField()
    order = models.IntegerField()

    tags = TaggableManager(through=CaseStudySnippetTag, blank=True)

    feed_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    panels = [
        FieldPanel('title'),
        ImageChooserPanel('feed_image'),
        FieldPanel('body', classname='description'),
        FieldPanel('active'),
        FieldPanel('order'),
        FieldPanel('tags'),
    ]


    def __str__(self):
        return self.title

    class Meta:
        ordering = ['order', 'title']


class AboutSnippetTag(TaggedItemBase):
    content_object = ParentalKey('home.AboutSnippet', on_delete=models.CASCADE, related_name='tagged_items')


@register_snippet
class AboutSnippet(ClusterableModel):
    title = models.CharField(max_length=255, blank=True)
    url = models.URLField(null=True, blank=True)
    text = models.CharField(max_length=255)
    body = RichTextField(blank=True)
    active = models.BooleanField()
    order = models.IntegerField()

    tags = TaggableManager(through=AboutSnippetTag, blank=True)

    feed_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    panels = [
        FieldPanel('title'),
        ImageChooserPanel('feed_image'),
        FieldPanel('body', classname='description'),
        FieldPanel('active'),
        FieldPanel('order'),
        FieldPanel('tags'),
    ]


    def __str__(self):
        return self.title

    class Meta:
        ordering = ['order', 'title']



class VisitorExpressSnippetTag(TaggedItemBase):
    content_object = ParentalKey('home.VisitorExpressSnippet', on_delete=models.CASCADE, related_name='tagged_items')

@register_snippet
class VisitorExpressSnippet(ClusterableModel):
    title = models.CharField(max_length=255, blank=True)
    url = models.URLField(null=True, blank=True)
    text = models.CharField(max_length=255)
    body = RichTextField(blank=True)
    active = models.BooleanField()
    order = models.IntegerField()

    tags = TaggableManager(through=VisitorExpressSnippetTag, blank=True)

    feed_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    panels = [
        FieldPanel('title'),
        ImageChooserPanel('feed_image'),
        FieldPanel('body', classname='description'),
        FieldPanel('active'),
        FieldPanel('order'),
        FieldPanel('tags'),
    ]


    def __str__(self):
        return self.title

    class Meta:
        ordering = ['order', 'title']


class Click2ParkSnippetTag(TaggedItemBase):
    content_object = ParentalKey('home.Click2ParkSnippet', on_delete=models.CASCADE, related_name='tagged_items')


@register_snippet
class Click2ParkSnippet(ClusterableModel):
    title = models.CharField(max_length=255, blank=True)
    url = models.URLField(null=True, blank=True)
    text = models.CharField(max_length=255)
    body = RichTextField(blank=True)
    active = models.BooleanField()
    order = models.IntegerField()

    tags = TaggableManager(through=Click2ParkSnippetTag, blank=True)

    feed_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    panels = [
        FieldPanel('title'),
        ImageChooserPanel('feed_image'),
        FieldPanel('body', classname='description'),
        FieldPanel('active'),
        FieldPanel('order'),
        FieldPanel('tags'),
    ]


    def __str__(self):
        return self.title

    class Meta:
        ordering = ['order', 'title']

class Journey2ShareSnippetTag(TaggedItemBase):
    content_object = ParentalKey('home.Journey2ShareSnippet', on_delete=models.CASCADE, related_name='tagged_items')


@register_snippet
class Journey2ShareSnippet(ClusterableModel):
    title = models.CharField(max_length=255, blank=True)
    url = models.URLField(null=True, blank=True)
    text = models.CharField(max_length=255)
    body = RichTextField(blank=True)
    active = models.BooleanField()
    order = models.IntegerField()

    tags = TaggableManager(through=Journey2ShareSnippetTag, blank=True)

    feed_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    panels = [
        FieldPanel('title'),
        ImageChooserPanel('feed_image'),
        FieldPanel('body', classname='description'),
        FieldPanel('active'),
        FieldPanel('order'),
        FieldPanel('tags'),
    ]


    def __str__(self):
        return self.title

    class Meta:
        ordering = ['order', 'title']



class TestPage(Page):
    body = RichTextField(blank=True)
    intro = RichTextField(blank=True)
    thank_you_text = RichTextField(blank=True)



# not needed
class CarouselItem(models.Model):
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )
    caption = models.CharField(max_length=255, blank=True)
    visitor_express_page = ParentalKey(VisitorExpressSnippet, related_name='carousel_links',null=True,blank=True)
    about_page = ParentalKey(AboutSnippet, related_name='carousel_links',null=True,blank=True)
    click2park_page = ParentalKey(Click2ParkSnippet, related_name='carousel_links',null=True,blank=True)
    journey2share_page = ParentalKey(Journey2ShareSnippet, related_name='carousel_links',null=True,blank=True)

    panels = [
        ImageChooserPanel('image'),
        FieldPanel('caption'),
    ]

    def __str__(self):
        return self.caption

home/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=254)
    message = forms.CharField(
        max_length=2000,
        widget=forms.Textarea(),
        help_text='Write here your message!'
    )
    source = forms.CharField(       # A hidden input for internal use
        max_length=50,              # tell from which page the user sent the message
        widget=forms.HiddenInput()
    )

    def clean(self):
        cleaned_data = super(ContactForm, self).clean()
        name = cleaned_data.get('name')
        email = cleaned_data.get('email')
        message = cleaned_data.get('message')
        if not name and not email and not message:
            raise forms.ValidationError('You have to write something!')

home/templates/home/yy/home_page.html
{% extends "base.html" %}

{% load wagtailcore_tags home_tags %}
{% load wagtailimages_tags %}


{% block body_class %}blue-grey darken-4{% endblock %}

{% load static %}

{% block extra_css %}
    <!-- Lato Font -->
    <title>NetFM</title>
    <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <!-- Stylesheet -->
    <link href="{% static "css/gallery-dark-materialize.min.css" %}" rel="stylesheet">
    <link href="{% static "css/nw.css" rel="stylesheet" %}">

    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock %}

  <body class="blue-grey darken-4">


  {% block content %}



    <!-- Navbar and Header -->
    <nav class="nav-extended nav-full-header z-depth-0 blue-grey darken-3">
      <div class="nav-background" id="embed">


  <!-- WCAG general accessibility recommendation is that media such as background video play through only once. Loop turned on for the purposes of illustration; if removed, the end of the video will fade in the same way created by pressing the "Pause" button  -->


          <iframe src="https://player.vimeo.com/video/250353021?background=1" width="2500" height="1405" border="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        <!-- <img class="active" src="http://placehold.it/1400x600" alt="control room"> -->
      </div>
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo"><i class="material-icons">all_inclusive</i>NetFM</a>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="/testform/#contact_us_modal">Contact us</a></li>
          <li><a href="/testform/#support_modal" >Support</a></li>
          <li><a class='/testform/dropdown-button/' href='#' data-activates='feature-dropdown' data-belowOrigin="true" data-constrainWidth="false">Login<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
        <!-- Dropdown Structure -->
        <ul id='feature-dropdown' class='dropdown-content'>
          <li><a href="https://click2park.co.uk/">Click2Park</a></li>
          <li><a href="https://visitor.express/login/">Visitor.Express</a></li>
        </ul>

      </div>

      <div class="nav-header valign-wrapper">



        <div class="center">
          <h1>Software by NetFM</h1>
            <div>Enabling Corporate Visitor Management</div>

        </div>
      </div>

      <!-- Fixed Masonry Filters -->
      <div class="categories-wrapper">
        <div class="categories-container">
          <ul class="categories container">
            <li class="active"><a href="/testform/#about">About</a></li>
            <li><a href="/testform/#visitorexpress">Visitor.Express</a></li>
            <li><a href="/testform/#click2park">Click2Park</a></li>
            <li><a href="/testform/#journey2share">Journey2Share</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <ul class="side-nav" id="nav-mobile">
      <li><a href="index.html"><i class="material-icons">all_inclusive</i>About</a></li>
      <li><a href="index-dark.html"><i class="material-icons">brightness_3</i>Contact us</a></li>
      <li><a href="https://github.com/NetFM/NetFM-Issue-Tracker/"><i class="material-icons">fullscreen</i>Support</a></li>
      <li><a href="https://click2park.co.uk"><i class="material-icons">swap_horiz</i>Click2Park</a></li>
      <li><a href="https://visitor.express/login/"><i class="material-icons">texture</i>Visitor.Express</a></li>
    </ul>

    <!-- Gallery -->
    <div id="portfolio" class="section gray">
      <div class="gallery row">

        {% AboutSnippets %}

        {% VisitorExpressSnippets %}

        {% Click2ParkSnippets %}

        {% Journey2ShareSnippets %}

      </div>

    </div><!-- /.container -->

      <div id="support_modal" class="modal">
        <div class="modal-content">
        <h4>Service status at {% now "h a" %} on {% now "l jS F" %}</h4>
        <div class="row">
        <div class="col s3">Web :  <i class="green material-icons">done</i></div>
        <div class="col s3">Email :  <i class="green material-icons">done</i></div>
        <div class="col s3">SMS :  <i class="green material-icons">done</i></div>
        </div>
            <div class=""row">
            <p class="col s12">No known current issues</p>
        </div>

              <h4>Support @ NetFM</h4>

        <p>For all support issues relating to both Visitor.Express please email <a href="mailto:support@visitor.express"><i class=" material-icons">email</i>support@visitor.express</a></p>
                <p>For all support issues relating to both Click2Parks please email <a href="mailto:support@click2park.co.uk"><i class=" material-icons">email</i>support@click2park.co.uk</a></p>

          <p>For any other issues please email  <a href="mailto:support@netfm.org"><i class=" material-icons">email</i>support@netfm.org</a></p>

      </div>
      </div>







<!-- Modal Structure -->
  <div id="contact_us_modal" class="modal">
    <div class="modal-content">
      <h4>Contact NetFM</h4>

            <!--{% csrf_token %} -->
            <!-- {{ form.as_p }} -->

  <div class="row">
    <!-- <form class="col s12" action="{% pageurl page %}" method="POST> -->
    <form action="{% pageurl page %}" method="POST">
      {% csrf_token %}
      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">account_circle</i>
          <input id="id_name" type="text" name="name" class="validate">
          <label for="id_name">Name</label>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">phone</i>
          <input id="id_telephone" type="tel" name="telephone" class="validate">
          <label for="id_telephone">Telephone</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">email</i>
          <input id="id_email" type="email" name="email" class="validate">
          <label for="id_email">Email</label>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">link</i>
          <input id="id_url" type="url" name="url" class="validate">
          <label for="id_url">Company URL</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <textarea id="id_question" type="text" name="question" class="materialize-textarea validate"></textarea>
          <label for="id_question">How can we help ?</label>
        </div>
      </div>


  </div>

    <div class="modal-footer">
        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right">send</i>

  </button>

    </div>
         </form>

  </div>
  </div>

  {% endblock %}

  {% block extra_js %}

    <!-- Core Javascript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="{% static "js/imagesloaded.pkgd.min.js" %}"></script>
    <script src="{% static "js/masonry.pkgd.min.js" %}"></script>
    <script src="https://cdn.jsdelivr.net/materialize/0.98.0/js/materialize.min.js"></script>
    <script src="{% static "js/color-thief.min.js" %}"></script>
    <script src="{% static "js/galleryExpand.js" %}"></script>
    <script src="{% static "js/init.js" %}"></script>
    <script>
(function ($) {
    $(function () {

        //initialize all modals
        $('.modal').modal();

        //now you can open modal from code
        // $('#modal1').modal('open');

        //or by click on trigger
        //$('.trigger-modal').modal();

    }); // end of document ready
})(jQuery); // end of jQuery name space


    $(document).ready(function(){

function resize(){

    alert('resise')

// Load Variables - we do this here so they are reset when the screen changes size.
var SW = $(window).width();
var VH = SW * 0.5625;
var SH = $(window).height();
var VW = SH * 1.777;

// Screen size check based on 16:9 ratio
if (SW > VW) {
$("#embed iframe").width(SW).height(VH).css("top", -(VH - SH) /2);
} else {
$("#embed iframe").height(SH).width(VW).css("left", -(VW - SW) /2);
}

// Confirmation
console.log("Resized")

} resize();

$(window).resize(function() {
resize();

});

}

</script>

{% endblock %}